# ─── SERVER ─────────────────────────────
server.port=${PORT:8080}

# ─── DATABASE (PostgreSQL - Neon) ───────
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_js6WaBOd1AEJ@ep-damp-forest-aoussjb3-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_js6WaBOd1AEJ
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA ────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ─── CORS ───────────────────────────────
app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:5500,http://localhost:5500,null

# ─── AUTH ───────────────────────────────
app.allowed-email-domain=@nmiet.edu.in
app.teacher-pin=teacher123

# ─── MAIL ───────────────────────────────
app.mail.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=renukakajale341@gmail.com
spring.mail.password=gwin xewc johg eqdp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.teacher-email=renukakajale341@gmail.com
